version: "2"
services:
  backend-app:
    build: ./backend-app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@55W03D
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  client-app:
    build: ./client-app
    links:
      - backend-app
    ports:
      - "3000:3000"